<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Customer;
use Illuminate\Support\Facades\DB;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing customers (optional - remove this line if you want to keep existing data)
        // Customer::truncate();

        $customers = [
            [
                'customer_name' => 'Rajesh Kumar',
                'customer_code' => 'CUS1001',
                'mobile_number' => '9876543210',
                'address' => '123 MG Road, Bangalore, Karnataka - 560001',
                'payment_terms' => 'Net 30',
                'gstin' => '29AAAAA0000A1Z5',
                'pan_number' => 'AAAAA1234A',
                'bank_name' => 'HDFC Bank',
                'branch_name' => 'MG Road Branch',
                'account_number' => '50100123456789',
                'ifsc_code' => 'HDFC0001234',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_name' => 'Priya Sharma',
                'customer_code' => 'CUS1002',
                'mobile_number' => '9876543211',
                'address' => '456 Park Street, Mumbai, Maharashtra - 400001',
                'payment_terms' => 'Net 15',
                'gstin' => '27BBBBB0000B1Z5',
                'pan_number' => 'BBBBB5678B',
                'bank_name' => 'ICICI Bank',
                'branch_name' => 'Park Street Branch',
                'account_number' => '50200123456789',
                'ifsc_code' => 'ICIC0001234',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_name' => 'Amit Patel',
                'customer_code' => 'CUS1003',
                'mobile_number' => '9876543212',
                'address' => '789 SG Highway, Ahmedabad, Gujarat - 380001',
                'payment_terms' => 'Net 45',
                'gstin' => '24CCCCC0000C1Z5',
                'pan_number' => 'CCCCC9012C',
                'bank_name' => 'SBI Bank',
                'branch_name' => 'SG Highway Branch',
                'account_number' => '50300123456789',
                'ifsc_code' => 'SBIN0001234',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_name' => 'Sunita Singh',
                'customer_code' => 'CUS1004',
                'mobile_number' => '9876543213',
                'address' => '321 CP Road, New Delhi, Delhi - 110001',
                'payment_terms' => 'Net 30',
                'gstin' => '07DDDDD0000D1Z5',
                'pan_number' => 'DDDDD3456D',
                'bank_name' => 'Axis Bank',
                'branch_name' => 'CP Road Branch',
                'account_number' => '50400123456789',
                'ifsc_code' => 'UTIB0001234',
                'status' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_name' => 'Vikram Reddy',
                'customer_code' => 'CUS1005',
                'mobile_number' => '9876543214',
                'address' => '654 Jubilee Hills, Hyderabad, Telangana - 500001',
                'payment_terms' => 'Net 60',
                'gstin' => '36EEEEE0000E1Z5',
                'pan_number' => 'EEEEE7890E',
                'bank_name' => 'HDFC Bank',
                'branch_name' => 'Jubilee Hills Branch',
                'account_number' => '50500123456789',
                'ifsc_code' => 'HDFC0005678',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_name' => 'Meera Joshi',
                'customer_code' => 'CUS1006',
                'mobile_number' => '9876543215',
                'address' => '987 FC Road, Pune, Maharashtra - 411001',
                'payment_terms' => 'Net 30',
                'gstin' => '27FFFFF0000F1Z5',
                'pan_number' => 'FFFFF1234F',
                'bank_name' => 'ICICI Bank',
                'branch_name' => 'FC Road Branch',
                'account_number' => '50600123456789',
                'ifsc_code' => 'ICIC0005678',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_name' => 'Rohit Agarwal',
                'customer_code' => 'CUS1007',
                'mobile_number' => '9876543216',
                'address' => '147 Park Circus, Kolkata, West Bengal - 700001',
                'payment_terms' => 'Net 15',
                'gstin' => '19GGGGG0000G1Z5',
                'pan_number' => 'GGGGG5678G',
                'bank_name' => 'SBI Bank',
                'branch_name' => 'Park Circus Branch',
                'account_number' => '50700123456789',
                'ifsc_code' => 'SBIN0005678',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_name' => 'Kavitha Nair',
                'customer_code' => 'CUS1008',
                'mobile_number' => '9876543217',
                'address' => '258 MG Road, Kochi, Kerala - 682001',
                'payment_terms' => 'Net 45',
                'gstin' => '32HHHHH0000H1Z5',
                'pan_number' => 'HHHHH9012H',
                'bank_name' => 'Canara Bank',
                'branch_name' => 'MG Road Branch',
                'account_number' => '50800123456789',
                'ifsc_code' => 'CNRB0001234',
                'status' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_name' => 'Deepak Gupta',
                'customer_code' => 'CUS1009',
                'mobile_number' => '9876543218',
                'address' => '369 MI Road, Jaipur, Rajasthan - 302001',
                'payment_terms' => 'Net 30',
                'gstin' => '08IIIII0000I1Z5',
                'pan_number' => 'IIIII3456I',
                'bank_name' => 'PNB Bank',
                'branch_name' => 'MI Road Branch',
                'account_number' => '50900123456789',
                'ifsc_code' => 'PUNB0001234',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_name' => 'Anita Verma',
                'customer_code' => 'CUS1010',
                'mobile_number' => '9876543219',
                'address' => '741 Mall Road, Chandigarh - 160001',
                'payment_terms' => 'Net 60',
                'gstin' => '04JJJJJ0000J1Z5',
                'pan_number' => 'JJJJJ7890J',
                'bank_name' => 'HDFC Bank',
                'branch_name' => 'Mall Road Branch',
                'account_number' => '51000123456789',
                'ifsc_code' => 'HDFC0009012',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_name' => 'Sanjay Mishra',
                'customer_code' => 'CUS1011',
                'mobile_number' => '9876543220',
                'address' => '852 Hazratganj, Lucknow, Uttar Pradesh - 226001',
                'payment_terms' => 'Net 30',
                'gstin' => '09KKKKK0000K1Z5',
                'pan_number' => 'KKKKK1234K',
                'bank_name' => 'ICICI Bank',
                'branch_name' => 'Hazratganj Branch',
                'account_number' => '51100123456789',
                'ifsc_code' => 'ICIC0009012',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_name' => 'Pooja Saxena',
                'customer_code' => 'CUS1012',
                'mobile_number' => '9876543221',
                'address' => '963 Civil Lines, Bhopal, Madhya Pradesh - 462001',
                'payment_terms' => 'Net 15',
                'gstin' => '23LLLLL0000L1Z5',
                'pan_number' => 'LLLLL5678L',
                'bank_name' => 'SBI Bank',
                'branch_name' => 'Civil Lines Branch',
                'account_number' => '51200123456789',
                'ifsc_code' => 'SBIN0009012',
                'status' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_name' => 'Ravi Iyer',
                'customer_code' => 'CUS1013',
                'mobile_number' => '9876543222',
                'address' => '159 T Nagar, Chennai, Tamil Nadu - 600001',
                'payment_terms' => 'Net 45',
                'gstin' => '33MMMMM0000M1Z5',
                'pan_number' => 'MMMMM9012M',
                'bank_name' => 'Indian Bank',
                'branch_name' => 'T Nagar Branch',
                'account_number' => '51300123456789',
                'ifsc_code' => 'IDIB0001234',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_name' => 'Neha Kapoor',
                'customer_code' => 'CUS1014',
                'mobile_number' => '9876543223',
                'address' => '357 Sector 17, Gurgaon, Haryana - 122001',
                'payment_terms' => 'Net 30',
                'gstin' => '06NNNNN0000N1Z5',
                'pan_number' => 'NNNNN3456N',
                'bank_name' => 'Axis Bank',
                'branch_name' => 'Sector 17 Branch',
                'account_number' => '51400123456789',
                'ifsc_code' => 'UTIB0009012',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_name' => 'Suresh Pillai',
                'customer_code' => 'CUS1015',
                'mobile_number' => '9876543224',
                'address' => '468 Whitefield, Bangalore, Karnataka - 560066',
                'payment_terms' => 'Net 60',
                'gstin' => '29OOOOO0000O1Z5',
                'pan_number' => 'OOOOO7890O',
                'bank_name' => 'HDFC Bank',
                'branch_name' => 'Whitefield Branch',
                'account_number' => '51500123456789',
                'ifsc_code' => 'HDFC0012345',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert all customers
        foreach ($customers as $customer) {
            Customer::create($customer);
        }
    }
}
